### ISSUE TITLE
GameHat Image

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#1]
**todo**
- 32 bit or 64 bit?
- Pi 3 or Pi4?
- do all the necessary installations, see [Game HAT wiki](https://www.waveshare.com/wiki/Game_HAT)

**done**
- [ ] image can be used for the FXGL games 
- [ ] sound is working 
- [ ] on/off switch is working
- [ ] touch events are working on integrated screen
