### ISSUE TITLE
include basic Java examples

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#12]
**todo**
include HelloWorld-type examples for CrowPi Image

- Plain Pi4J. Use "Up-Button" of CrowPi and attach some listeners to it 
- Plain JavaFX. Including some sound elements (will currently not work)

**done**
- [x] Plain Pi4J can be started via ssh.
- [x] Plain JavaFX can be started via Java-Kiosk
- [x] README explains both examples
