### ISSUE TITLE
Picade Image

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#2]
**todo**
- for Picade games we use Pi 4
- 64 bits should be a better choice (but needs more Gluon work)
  - requires some adjustment to the Packer QEMU builder
- do all the necessary installations, see [Picade Assembly](https://learn.pimoroni.com/tutorial/sandyj/assembling-your-picade-console)

`curl https://get.pimoroni.com/picadehat | bash`

**done**
- [x] image can be used for the FXGL games on Picade console
- [x] game sound is working 
- [x] on/off switch is working
- [ ] image starts on RaspiOS without any error messages
